http:
    rootPath: /service/*

spinner:
    foods:
      - key: bacon
        description: "Bacon Strips"
        weight: 2
      - key: chips
        description: Chips
        weight: 3
      - key: cupcakes
        description: Cupcakes
      - key: fruit
        description: Fruit
      - key: icecream
        description: "Ice Cream Bars"
        weight: 2
      - key: pie
        description: Pie
      - key: pizza
        description: Pizza
      - key: tacos
        description: Tacos
      - key: wings
        description: "Buffalo Wings"
    drinks:
      - key: juiceboxes
        description: "Juice Boxes"
        weight: 3
      - key: soda
        description: Soda
        weight: 3
      - key: water
        description: Water
        weight: 3
    supplies:
      - key: plasticware
        description: "Plastic forks, spoons, knives"
      - key: napkins
        description: Napkins
    nuisances:
      - key: ants
        description: Ants
        weight: 3
        impact: reduces-food
      - key: rain
        description: Rain
        impact: wipeout
      - key: sunburn
        description: Sunburn
        impact: lose-turn
    preventions:
      - key: sunscreen
        description: Sunscreen
        counteracts: sunburn
      - key: bugspray
        description: "Bug Spray"
        counteracts: ants
      - key: umbrella
        description: Umbrella
        counteracts: rain
